# Generated by Django 5.2.7 on 2025-11-17 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCancellationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Lý do yêu cầu hủy sự kiện')),
                ('refund_policy', models.TextField(blank=True, help_text='Chính sách hoàn tiền cho người tham gia')),
                ('alternative_action', models.TextField(blank=True, help_text='Hành động thay thế (hoãn, chuyển địa điểm, etc)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_comment', models.TextField(blank=True, help_text='Nhận xét của admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_requests', to='event_management.event')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_cancellations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'event_cancellation_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event', 'status'], name='event_cance_event_i_13caf7_idx'), models.Index(fields=['status', '-created_at'], name='event_cance_status_8c6073_idx')],
            },
        ),
    ]
