# Generated by Django 5.2.7 on 2025-11-18 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0002_eventcancellationrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True, verbose_name='Saved At')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='event_management.event', verbose_name='Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_events', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Saved Event',
                'verbose_name_plural': 'Saved Events',
                'db_table': 'saved_events',
                'ordering': ['-saved_at'],
                'indexes': [models.Index(fields=['user', '-saved_at'], name='saved_event_user_id_1692b0_idx'), models.Index(fields=['event'], name='saved_event_event_i_335000_idx')],
                'unique_together': {('user', 'event')},
            },
        ),
    ]
