# Generated by Django 5.2.7 on 2025-12-21 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='reportexportjob',
            new_name='report_expo_status_c52c55_idx',
            old_name='reportexport_status_idx',
        ),
    ]
