# Generated by Django 5.2.7 on 2025-12-22 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('event_approved', 'Event Approved'), ('event_rejected', 'Event Rejected'), ('event_reminder', 'Event Reminder'), ('event_cancelled', 'Event Cancelled'), ('event_updated', 'Event Updated'), ('registration_confirmed', 'Registration Confirmed'), ('event_pending', 'Event Pending Approval'), ('new_registration', 'New Registration'), ('event_full', 'Event Full'), ('low_attendance', 'Low Attendance Alert'), ('feedback_received', 'Feedback Received'), ('feedback_request', 'Feedback Request'), ('high_risk_event', 'High Risk Event'), ('club_violation', 'Club Violation'), ('system_issue', 'System Issue'), ('system_stats', 'System Statistics'), ('club_announcement', 'Club Announcement'), ('system', 'System Notification')], max_length=50),
        ),
    ]
